version: 2.1

orbs:
  base: codacy/base@10.1.3
  codacy: codacy/base@10.1.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Generate Code Coverage Report
          command: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report -Dmaven.test.failure.ignore=true
      - codacy/upload-coverage:
          coverage_report_path: target/site/jacoco/jacoco.xml
          project_token: 4046e2c81781480f92e3b01e950036f7

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build
