version: 2.1

orbs:
  codacy: codacy/codacy-analysis-orb@1.1.1

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-11
    steps:
      - checkout
      - run: mvn clean install
      - codacy/upload:
          coverage_report: target/site/jacoco/jacoco.xml
          api_token: t2xwSWdp3BmLbXuahtSn

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
