name: Codacy Maven Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CODACY_PROJECT_TOKEN: 4046e2c81781480f92e3b01e950036f7

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn test
    - name: Upload coverage report to Codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml -t 4046e2c81781480f92e3b01e950036f7
    env:
          CODACY_PROJECT_TOKEN: 4046e2c81781480f92e3b01e950036f7
